name: SonarCloud Analysis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run test with code coverage
      run: npm test
    - name: Sonarqube Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
